exit 1 for "pytest first failure"

diff --git a/.github/workflows/wipac-cicd.yml b/.github/workflows/wipac-cicd.yml
--- a/.github/workflows/wipac-cicd.yml
+++ b/.github/workflows/wipac-cicd.yml
@@ -456,7 +456,13 @@ jobs:
       - name: pytest first failure
         if: always()
         run: |
-          cat $( grep -l -m 1 *.test.out -e "= FAILURES =" | head -1 ) || echo "not found"
+          file=$(grep -l -m 1 "= FAILURES =" *.test.out | head -1)
+          if [ -n "$file" ]; then
+              cat $file
+              exit 1
+          else
+              echo "not found"
+          fi
 
       - name: pytest container outputs
         if: always()
