Upgrade CI; No More PyPI; UTC Logs [minor] (#114)
Co-authored-by: github-actions <github-actions@github.com>

diff --git a/.github/workflows/wipac-cicd.yml b/.github/workflows/wipac-cicd.yml
--- a/.github/workflows/wipac-cicd.yml
+++ b/.github/workflows/wipac-cicd.yml
@@ -10,7 +10,7 @@ on:
 # not using concurrency -- it makes A/B debugging difficult. Now, manually cancel prev tests if needed
 
 env:
-  RABBITMQ_IMAGE_TAG: bitnami/rabbitmq:3.13.5
+  RABBITMQ_IMAGE_TAG: bitnamilegacy/rabbitmq:3.13.5
   PULSAR_IMAGE_TAG: apachepulsar/pulsar:2.6.0
   NATS_IMAGE_TAG: nats:2.10.18
   #
@@ -35,9 +35,11 @@ jobs:
     outputs:
       matrix: ${{ steps.versions.outputs.matrix }}
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
       - id: versions
-        uses: WIPACrepo/wipac-dev-py-versions-action@v2.5
+        uses: WIPACrepo/wipac-dev-py-versions-action@v2.7
 
 
   #############################################################################
@@ -52,11 +54,15 @@ jobs:
       matrix:
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
       - uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.py3 }}
-      - uses: WIPACrepo/wipac-dev-flake8-action@v1.2
+      - uses: WIPACrepo/wipac-dev-flake8-action@v1.3
+        with:
+          max-complexity: 12  # ideal is ~10-15
 
   mypy:
     needs: [ py-versions ]
@@ -66,7 +72,10 @@ jobs:
       matrix:
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
       - uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.py3 }}
@@ -80,19 +89,16 @@ jobs:
   py-setup:
     runs-on: ubuntu-latest
     steps:
-      - if: github.actor != 'dependabot[bot]'
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v5
         with:
-          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
-      - if: github.actor != 'dependabot[bot]'
-        uses: WIPACrepo/wipac-dev-py-setup-action@v4.4
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          ref: ${{ github.ref }}  # dont lock to sha (action needs to push)
+      - uses: WIPACrepo/wipac-dev-py-setup-action@v5.2
         with:
-          python_min: "3.12"
-          python_max: "3.12"
-          keywords_comma: "pilot, Observation Management Service, Event Workflow Management Service, EWMS, message passing, MQ task"
-          pypi_name: ewms-pilot
-          author: WIPAC Developers
-          author_email: developers@icecube.wisc.edu
+          mode: PACKAGING
+          python_min: 3.12
+          keywords_comma: "pilot, task pilot, Observation Management Service, Event Workflow Management System, EWMS, message passing, MQ"
+          auto_mypy_option: True
 
   py-dependencies:
     needs: [ py-versions ]
@@ -101,15 +107,13 @@ jobs:
       group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job }}
       cancel-in-progress: true
     steps:
-      - if: github.actor != 'dependabot[bot]'
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v5
         with:
-          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # fyi, dependabot can't access normal secrets
-      - if: github.actor != 'dependabot[bot]'
-        name: build all images
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
+      - name: build all images
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           set -x
           
           mkdir docker-build-logs/ && trap 'rm -rf docker-build-logs/' EXIT
@@ -119,7 +123,7 @@ jobs:
           docker build --tag "default:py-dep-this" . \
               >> docker-build-logs/default.docker-build.out 2>&1 & pidlist="$pidlist $!"
           
-          # build all dockerfiles
+          # build all dockerfiles -- all in background/parallel
           for py in $(echo ${{ needs.py-versions.outputs.matrix }} | sed 's/[][]//g; s/,/ /g'); do
               docker pull python:$py  # pre-pull to speed up dependent images
               for flavor in rabbitmq pulsar nats; do
@@ -155,10 +159,7 @@ jobs:
           
           docker system prune --force  # save disk space
 
-      - if: github.actor != 'dependabot[bot]'
-        uses: WIPACrepo/wipac-dev-py-dependencies-action@v2.2
-        with:
-          use_directory: true
+      - uses: WIPACrepo/wipac-dev-py-dependencies-action@v3.1
 
 
   ############################################################################
@@ -168,7 +169,10 @@ jobs:
   test-build-docker:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
       - uses: docker/setup-buildx-action@v3
       - uses: docker/build-push-action@v5
         with:
@@ -189,17 +193,18 @@ jobs:
       EWMS_PILOT_QUEUE_OUTGOING: bar
       EWMS_PILOT_TIMEOUT_QUEUE_WAIT_FOR_FIRST_MESSAGE: 1  # added to figure out https://github.com/WIPACrepo/wipac-dev-tools/pull/106, not needed but not doing any harm
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
       - name: build docker image
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker build --tag ${{ env.DOCKER_IMAGE_NAME }} .
           docker images
       - name: test
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           set -ex
           
           docker run --rm \
@@ -229,16 +234,18 @@ jobs:
       matrix:
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
       - uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.py3 }}
       - name: pytest
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           pip install .[test]
-          pytest -vvv tests/unit
+          pytest -vvv --asyncio-mode=auto tests/unit
 
   integration-tests:
     needs: [ py-versions ]
@@ -250,7 +257,10 @@ jobs:
         py3: ${{ fromJSON(needs.py-versions.outputs.matrix) }}
         broker_client: [ pulsar, rabbitmq, nats ]
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
+        with:
+          ref: ${{ github.sha }}  # lock to triggered commit (github.ref is dynamic)
+          fetch-depth: 0  # setuptools-scm needs to access git tags
       - uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.py3 }}
@@ -264,8 +274,7 @@ jobs:
       - if: ${{ matrix.container_platform == 'docker' }}
         name: install sysbox (needed for docker-in-docker)
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker --version
           echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           temp_dir=$(mktemp -d) && cd $temp_dir
@@ -283,8 +292,7 @@ jobs:
 
       - name: build docker image
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker build --tag ${{ env.DOCKER_IMAGE_NAME }} \
               --build-arg="PYTHON=${{ matrix.py3 }}" \
               --build-arg="FLAVOR=${{ matrix.broker_client }},test" \
@@ -294,8 +302,7 @@ jobs:
 
       - name: pre-pull & save images for testing
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           set -x
           mkdir saved-images/
           
@@ -310,7 +317,7 @@ jobs:
                       break
                   elif [[ $exit_code -eq 255 ]]; then
                       # docker hub rate limiting
-                      echo "Command failed with exit code 255. Retry $i/$max_retries..."
+                      echo "::warning::Command failed with exit code 255. Retry $i/$max_retries..."
                   else
                       exit $exit_code
                   fi
@@ -335,16 +342,14 @@ jobs:
       - if: ${{ matrix.container_platform == 'apptainer' }}
         name: build apptainer image
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker images
           apptainer build $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif docker-daemon://${{ env.DOCKER_IMAGE_NAME }}:latest
           ls -lh $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif
 
       - name: get list of pytest tests
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           pip install .[test]  # for the for-loop below
           pytest --collect-only -q --disable-warnings tests/integration/ | head -n -2 > $SORTED_LIST_OF_TESTS_FILE
           cat $SORTED_LIST_OF_TESTS_FILE
@@ -352,8 +357,7 @@ jobs:
       - if: ${{ matrix.container_platform == 'docker' }}
         name: set up docker network
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           # we're connecting all the containers (broker + apps) in the same docker network
           # create common network -- https://github.com/nestybox/sysbox/blob/master/docs/quickstart/kind.md#k8s-cluster-on-user-defined-bridge-networks
           docker network create mynet
@@ -383,7 +387,8 @@ jobs:
               export EWMS_PILOT_QUEUE_INCOMING_BROKER_ADDRESS="localhost"  # localhost b/c using --network=host
               export EWMS_PILOT_QUEUE_OUTGOING_BROKER_ADDRESS="localhost"  # localhost b/c using --network=host
           else
-              exit 2  # unknown container_platform
+              echo "::error::unknown container_platform: ${{ matrix.container_platform }}"
+              exit 2
           fi
           docker ps
           
@@ -428,11 +433,18 @@ jobs:
                       --mount type=bind,source=$(pwd)/saved-images,target=/saved-images/ \
                       --mount type=bind,source=$(pwd)/cvmfs/dummy-1/dir-A,target=/cvmfs/dummy-1/dir-A,readonly \
                       --mount type=bind,source=$(pwd)/cvmfs/dummy-2/dir-B,target=/cvmfs/dummy-2/dir-B,readonly \
+                      --mount type=bind,source="$(realpath ${{ github.workspace }}/$(dirname $test))",target="/app/$(dirname $test)",readonly \
                       $(env | grep '^EWMS_' | awk '$0="--env "$0') \
                       $(env | grep '^_EWMS_' | awk '$0="--env "$0') \
                       --env CI_TEST_ALPINE_PYTHON_IMAGE="python:alpine" \
                       --env CI=$CI \
-                      ${{ env.DOCKER_IMAGE_NAME }} /bin/bash -c "docker load -i /saved-images/python-alpine.tar && ls -l && ls -l / && docker images && pytest -vvv -s $test" \
+                      ${{ env.DOCKER_IMAGE_NAME }} /bin/bash -c "\
+                          docker load -i /saved-images/python-alpine.tar && \
+                          ls -l && \
+                          ls -l / && \
+                          docker images && \
+                          pytest -vvv --asyncio-mode=auto -s $test \
+                      " \
                       >> $(basename $test).test.out 2>&1 & pidlist="$pidlist $!"
                       # 2>&1   # -- uncomment to debug
                       # exit 5 # -- uncomment to debug
@@ -452,6 +464,7 @@ jobs:
                       --mount type=bind,source=$(pwd)/saved-images,target=/saved-images/ \
                       --mount type=bind,source=$(pwd)/cvmfs/dummy-1/dir-A,target=/cvmfs/dummy-1/dir-A,readonly \
                       --mount type=bind,source=$(pwd)/cvmfs/dummy-2/dir-B,target=/cvmfs/dummy-2/dir-B,readonly \
+                      --mount type=bind,source="$(realpath ${{ github.workspace }}/$(dirname $test))",target="/app/$(dirname $test)",readonly \
                       $(env | grep '^EWMS_' | awk '$0="--env "$0') \
                       $(env | grep '^_EWMS_' | awk '$0="--env "$0') \
                       --env CI_TEST_ALPINE_PYTHON_IMAGE="/saved-images/python_alpine_sandbox/" \
@@ -460,16 +473,19 @@ jobs:
                       --env CI=$CI \
                       --workdir "$temp_dir" -B "$temp_dir" \
                       $(basename ${{ env.DOCKER_IMAGE_NAME }}).sif \
-                      /bin/bash -c "ls -l && ls -l / && pytest -vvv -s /app/$test" \
+                      /bin/bash -c "\
+                          ls -l && \
+                          ls -l / && \
+                          pytest -vvv --asyncio-mode=auto -s /app/$test \
+                      " \
                       >> $(basename $test).test.out 2>&1 & pidlist="$pidlist $!"
                       # 2>&1   # -- uncomment to debug
                       # exit 5 # -- uncomment to debug
                   set +x
           
               else
-          
-                  exit 2  # unknown container_platform
-          
+                  echo "::error::unknown container_platform: ${{ matrix.container_platform }}"
+                  exit 2
               fi
           
               sleep .1  # little sleep to help logs
@@ -483,7 +499,7 @@ jobs:
               date --rfc-3339=seconds
               echo "waiting for $pid..."
               if ! wait -n $pid; then
-                  echo "ERROR: test(s) failed (ctrl+f $pid to match)"
+                  echo "::error::test(s) failed (ctrl+f $pid to match)"
                   sleep 5  # may need to wait for output files to be written
                   kill $pidlist 2>/dev/null
                   exit 1
@@ -494,22 +510,20 @@ jobs:
       - name: pytest first failure
         if: always()
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           file=$(grep -l -m 1 "= FAILURES =" *.test.out 2>/dev/null | head -1 || true)
           if [[ -n "$file" ]]; then
               cat "$file"
-              echo "^^^^ this is the pytest out file -- this step exited with 1 because this *pytest* failed -- the ci step is okay"
+              echo "::error::^^^^ this is the pytest out file -- this step exited with 1 because this *pytest* failed -- the ci step is okay"
               exit 1
           else
-              echo "not found"
+              echo "::warning::pytest failure not found -- either all tests passed, or a test container failed before pytesting"
           fi
 
       - name: pytest container outputs
         if: always()
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           sleep 15  # sleep a bit more in case there are additional failures we want to dig for
           cat $SORTED_LIST_OF_TESTS_FILE
           while read test; do
@@ -519,15 +533,14 @@ jobs:
               if [ -f $(basename $test).test.out ]; then
                   cat $(basename $test).test.out
               else
-                  echo "CI: output file does not exist"
+                  echo "::warning::output file does not exist, test may not have be started -- look at above test logs"
               fi
           done < $SORTED_LIST_OF_TESTS_FILE
 
       - name: broker output
         if: always()
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           set -x
           cat ./broker.out
           if [ -n "$(ls -A ./broker_logs/ 2>/dev/null)" ]; then
@@ -538,8 +551,7 @@ jobs:
       - name: broker docker logs
         if: always()
         run: |
-          set -euo pipefail
-          echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+          set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
           docker logs $BROKER_CONTAINER_NAME || true
 
 
@@ -547,9 +559,9 @@ jobs:
   # GITHUB & PYPI RELEASE
   #############################################################################
 
-  release:
-    # only run on main/master/default
-    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
+  tag-and-release:
+    # only run on main/default
+    if: format('refs/heads/{0}', github.event.repository.default_branch) == github.ref
     needs: [
       py-versions,
       flake8,
@@ -561,25 +573,11 @@ jobs:
       unit-tests,
       vanilla-run
     ]
-    runs-on: ubuntu-latest
-    concurrency: release  # prevent any possible race conditions
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # using 'GITHUB_TOKEN' does not trigger ci on push
-      # Python-Package Version Bump
-      - uses: python-semantic-release/python-semantic-release@v9.8.1
-        id: psr-psr
-        with:
-          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # using 'GITHUB_TOKEN' does not trigger ci on push
-      # PyPI Release
-      - uses: pypa/gh-action-pypi-publish@v1.12.4
-        if: steps.psr-psr.outputs.released == 'true'
-        with:
-          password: ${{ secrets.PYPI_TOKEN }}
-      # GitHub Release
-      - uses: python-semantic-release/upload-to-gh-release@v9.8.1
-        if: steps.psr-psr.outputs.released == 'true'
-        with:
-          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # using 'GITHUB_TOKEN' does not trigger ci on push
+    uses: WIPACrepo/wipac-dev-workflows/.github/workflows/tag-and-release.yml@v1.11
+    permissions: # for GITHUB_TOKEN
+      contents: write
+    with:
+      project-type: python
+      python-version: "${{ fromJSON(needs.py-versions.outputs.matrix)[0] }}"
+      release-artifacts: |
+        py-dependencies-logs
