Add Test: Run Default Container (#99)

diff --git a/.github/workflows/wipac-cicd.yml b/.github/workflows/wipac-cicd.yml
--- a/.github/workflows/wipac-cicd.yml
+++ b/.github/workflows/wipac-cicd.yml
@@ -160,6 +160,44 @@ jobs:
           cache-to: type=gha,mode=min
           tags: ${{ env.DOCKER_IMAGE_NAME }}:local
 
+  vanilla-run:
+    needs: [ py-versions ]
+    runs-on: ubuntu-latest
+    env:
+      EWMS_PILOT_QUEUE_INCOMING_BROKER_TYPE: rabbitmq
+      EWMS_PILOT_QUEUE_OUTGOING_BROKER_TYPE: rabbitmq
+      EWMS_PILOT_QUEUE_INCOMING_BROKER_ADDRESS: blah
+      EWMS_PILOT_QUEUE_OUTGOING_BROKER_ADDRESS: blah
+      EWMS_PILOT_QUEUE_INCOMING: foo
+      EWMS_PILOT_QUEUE_OUTGOING: bar
+      EWMS_PILOT_TIMEOUT_QUEUE_WAIT_FOR_FIRST_MESSAGE: 1  # added to figure out https://github.com/WIPACrepo/wipac-dev-tools/pull/106, not needed but not doing any harm
+    steps:
+      - uses: actions/checkout@v4
+      - name: build docker image
+        run: |
+          docker build --tag ${{ env.DOCKER_IMAGE_NAME }} .
+          docker images
+      - run: |
+          set -ex
+          
+          docker run --rm \
+              $(env | grep '^EWMS_' | awk '$0="--env "$0') \
+              ${{ env.DOCKER_IMAGE_NAME }} \
+              2>&1 | tee -a test.out 
+          cat test.out
+          
+          # The intent of this test is to confirm that the pilot runs as a CL script
+          #   without error. Real testing is done in 'integration-tests'. This "test"
+          #   ends on the following error, which is relatively early in the pilot...
+          
+          expected="RuntimeError: Task image was not provided."
+          if [[ $( tail -n 1 test.out ) == "$expected" ]]; then
+              echo "passed! (iow, this is the correct error ^^^)"
+          else
+              echo "ERROR: the pilot did not fail as expected"
+              exit 1
+          fi
+
 
   integration-tests:
     needs: [ py-versions ]
@@ -438,7 +476,8 @@ jobs:
       py-setup,
       py-dependencies,
       test-build-docker,
-      integration-tests
+      integration-tests,
+      vanilla-run
     ]
     runs-on: ubuntu-latest
     concurrency: release  # prevent any possible race conditions
